const {chromium,expect}=require(process.env.PLAYWRIGHT_MODULE||'@playwright/test');
const path=require('node:path');const os=require('node:os');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
await context.addInitScript(()=>{const f=window.fetch.bind(window);window.fetch=(u,o)=>f(typeof u==='string'?u.replace(':8001/',':8012/'):u,o);const W=window.WebSocket;window.WebSocket=class extends W{constructor(u,p){super(String(u).replace(':8001/',':8012/'),p);}};});
const api=async(route,body,token)=>{const r=await fetch('http://127.0.0.1:8012'+route,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(await r.text());return r.json();};
try{const c=await api('/rooms',{name:'疯狂数钱',brand:'EventPlay 财富挑战',mechanic:'money',theme:'gold',duration:60,participants:20,teams:'招财队,丰收队,好运队,开心队'});
const id=c.room.id,command=action=>api('/rooms/'+id+'/command',{action},c.token);
const p=await api('/rooms/'+id+'/join',{name:'数钱玩家',team:0});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:4191/live/screen/'+id);
const stage=page.locator('[data-money-stage]');await expect(stage).toBeVisible();await expect(page.getByText('扫码加入 · 等待开场',{exact:true})).toBeVisible();
await command('start');await api('/rooms/'+id+'/tap',{seq:1,kind:'swipe'},p.token);
await expect(stage).toHaveAttribute('data-moving','true');await expect(stage.getByText('领先中',{exact:true})).toHaveCount(1);
await stage.screenshot({path:path.join(os.tmpdir(),'eventplay-money-desktop.png')});
await page.setViewportSize({width:390,height:844});await expect.poll(async()=>(await stage.boundingBox()).width).toBeLessThanOrEqual(390);await stage.screenshot({path:path.join(os.tmpdir(),'eventplay-money-mobile.png')});
expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
await command('pause');await expect(stage).toHaveAttribute('data-moving','false');await expect(stage.getByText('暂停数钱',{exact:true})).toBeVisible();
expect((await api('/rooms/'+id+'/tap',{seq:2,kind:'swipe'},p.token)).accepted).toBe(false);
await command('finish');await expect(stage.getByRole('list',{name:'财富最终排名'}).getByRole('listitem')).toHaveCount(4);
if(errors.length)throw Error(errors.join('\n'));console.log('PASS money: 4 teams, real scores, QR, mobile, pause, final ranking');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
